spring:
  application:
    name: EmpikTask
  datasource:
    url: jdbc:h2:mem:complaintsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/v1-initial-schema.sql

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

ip:
  api:
    url: http://ip-api.com/json/
    timeout: 1h
    max-size: 1000
    fallback-country: Unknown
